# Generated by Django 4.1.4 on 2022-12-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a_gol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_gol',
            field=models.IntegerField(default=0),
        ),
    ]
