# Generated by Django 4.1.4 on 2022-12-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTeam',
        ),
    ]
